var ghgData = [
    {
        "property_name": "2850 Hylan Blvd",
        "address_1": "2850 HYLAN BLVD",
        "city": "Staten Island",
        "postal_code": 10306,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 3500,
        "multifamily_housing_total_number_of_residential_living_units": 4,
        "year_built": 1950,
        "total_ghg_intensity": 59.9,
        "latitude": 40.563453,
        "longitude": -74.116513
    },
    {
        "property_name": "30-15 Apartments LLC",
        "address_1": "30-15 33rd street",
        "city": "Astoria",
        "postal_code": 11103,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 34200,
        "multifamily_housing_total_number_of_residential_living_units": 41,
        "year_built": 1931,
        "total_ghg_intensity": 44.4,
        "latitude": 40.765506,
        "longitude": -73.920295
    },
    {
        "property_name": "2086 2nd Ave",
        "address_1": "2086 2nd Ave",
        "city": "Manhattan",
        "postal_code": 10029,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 124000,
        "multifamily_housing_total_number_of_residential_living_units": 117,
        "year_built": 1961,
        "total_ghg_intensity": 37,
        "latitude": 40.791363,
        "longitude": -73.941885
    },
    {
        "property_name": "280 Malden Pl",
        "address_1": "280 MALDEN PL",
        "city": "Staten Island",
        "postal_code": 10306,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 6700,
        "multifamily_housing_total_number_of_residential_living_units": 7,
        "year_built": 1950,
        "total_ghg_intensity": 33.3,
        "latitude": 40.562001,
        "longitude": -74.116061
    },
    {
        "property_name": "243 WEST 63rd STREET - 41961",
        "address_1": "243 WEST 63rd STREET",
        "city": "New York",
        "postal_code": 10023,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 27152,
        "multifamily_housing_total_number_of_residential_living_units": 49,
        "year_built": 1907,
        "total_ghg_intensity": 32.4,
        "latitude": 40.773885,
        "longitude": -73.988067
    },
    {
        "property_name": "GGHC - 25 Montgomery St",
        "address_1": "25 Montgomery Street",
        "city": "New York",
        "postal_code": 10002,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 141513,
        "multifamily_housing_total_number_of_residential_living_units": 141,
        "year_built": 1963,
        "total_ghg_intensity": 31.6,
        "latitude": 40.713434,
        "longitude": -73.985077
    },
    {
        "property_name": "2022 Copy of Clearview 5 Bldg C-1",
        "address_1": "157-58 17 Rd.",
        "city": "New York",
        "postal_code": 11357,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 4200,
        "multifamily_housing_total_number_of_residential_living_units": 4,
        "year_built": 1951,
        "total_ghg_intensity": 31.1,
        "latitude": 40.782606,
        "longitude": -73.803703
    },
    {
        "property_name": "2022 Copy of Clearview 5 Bldg H10-H11",
        "address_1": "163-04 16 Road",
        "city": "New York",
        "postal_code": 11357,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 12900,
        "multifamily_housing_total_number_of_residential_living_units": 32,
        "year_built": 1951,
        "total_ghg_intensity": 29.4,
        "latitude": 40.783727,
        "longitude": -73.799778
    },
    {
        "property_name": "2085 2nd Ave",
        "address_1": "2085 2nd Ave",
        "city": "Manhattan",
        "postal_code": 10029,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 128000,
        "multifamily_housing_total_number_of_residential_living_units": 117,
        "year_built": 1961,
        "total_ghg_intensity": 29,
        "latitude": 40.791593,
        "longitude": -73.941744
    },
    {
        "property_name": "2085 2nd Ave",
        "address_1": "2085 2nd Ave",
        "city": "Manhattan",
        "postal_code": 10029,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 128000,
        "multifamily_housing_total_number_of_residential_living_units": 117,
        "year_built": 1961,
        "total_ghg_intensity": 29,
        "latitude": 40.791593,
        "longitude": -73.941744
    },
    {
        "property_name": "Betances III, 18 411 E136th Street",
        "address_1": "411 E136th Street",
        "city": "The Bronx",
        "postal_code": 10454,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 17629,
        "multifamily_housing_total_number_of_residential_living_units": 19,
        "year_built": 1973,
        "total_ghg_intensity": 27.6,
        "latitude": 40.807562,
        "longitude": -73.923225
    },
    {
        "property_name": "RY - 671 Lincoln Ave",
        "address_1": "671 Lincoln Avenue",
        "city": "Brooklyn",
        "postal_code": 11208,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "100% Yes",
        "multifamily_housing_gross_floor_area_ft": 323070,
        "multifamily_housing_total_number_of_residential_living_units": 319,
        "year_built": 1975,
        "total_ghg_intensity": 26.1,
        "latitude": 40.672955,
        "longitude": -73.866507
    },
    {
        "property_name": "The L @ 30th drive",
        "address_1": "25-32 30th drive",
        "city": "Astoria",
        "postal_code": 11102,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 43552,
        "multifamily_housing_total_number_of_residential_living_units": 39,
        "year_built": 2011,
        "total_ghg_intensity": 25.9,
        "latitude": 40.766618,
        "longitude": -73.925716
    },
    {
        "property_name": "29 Primrose Pl",
        "address_1": "29 PRIMROSE PL",
        "city": "Staten Island",
        "postal_code": 10306,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 6700,
        "multifamily_housing_total_number_of_residential_living_units": 7,
        "year_built": 1950,
        "total_ghg_intensity": 25.7,
        "latitude": 40.562548,
        "longitude": -74.115734
    },
    {
        "property_name": "30 East 76th St Condominium",
        "address_1": "971 Madison Avenue",
        "city": "Manhattan",
        "postal_code": 10021,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 17942,
        "multifamily_housing_total_number_of_residential_living_units": 15,
        "year_built": 1928,
        "total_ghg_intensity": 24.7,
        "latitude": 40.774223,
        "longitude": -73.963643
    },
    {
        "property_name": "4113 Broadway AKA 636 West 174th Street",
        "address_1": "636 West 174th Street",
        "city": "New York",
        "postal_code": 10033,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "100% Yes",
        "multifamily_housing_gross_floor_area_ft": 46036,
        "multifamily_housing_total_number_of_residential_living_units": 46,
        "year_built": 1926,
        "total_ghg_intensity": 24.1,
        "latitude": 40.845509,
        "longitude": -73.938881
    },
    {
        "property_name": "150 East 72nd St",
        "address_1": "150 East 72nd St",
        "city": "New York",
        "postal_code": 10021,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 67694,
        "multifamily_housing_total_number_of_residential_living_units": 25,
        "year_built": 1914,
        "total_ghg_intensity": 22,
        "latitude": 40.770264,
        "longitude": -73.96185
    },
    {
        "property_name": "Glenwood - The Pavilion (500 East 77th Street)",
        "address_1": "500 East 77th Street",
        "city": "New York",
        "postal_code": 10162,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 248361,
        "multifamily_housing_total_number_of_residential_living_units": 210,
        "year_built": 1964,
        "total_ghg_intensity": 20.8,
        "latitude": 40.769975,
        "longitude": -73.951186
    },
    {
        "property_name": "5 Cabrini Blvd",
        "address_1": "5 Cabrini Blvd",
        "city": "New York",
        "postal_code": 10033,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "100% Yes",
        "multifamily_housing_gross_floor_area_ft": 28835,
        "multifamily_housing_total_number_of_residential_living_units": 35,
        "year_built": 1916,
        "total_ghg_intensity": 20.6,
        "latitude": 40.84856,
        "longitude": -73.941225
    },
    {
        "property_name": "60 First Ave - 7144",
        "address_1": "60 First Ave",
        "city": "New York",
        "postal_code": 10009,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 214280,
        "multifamily_housing_total_number_of_residential_living_units": 214,
        "year_built": 1964,
        "total_ghg_intensity": 20.1,
        "latitude": 40.724905,
        "longitude": -73.987243
    },
    {
        "property_name": "DOZIS: 31-60 33rd St",
        "address_1": "31-60 33rd St",
        "city": "Queens",
        "postal_code": 11106,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 29960,
        "multifamily_housing_total_number_of_residential_living_units": 39,
        "year_built": 1926,
        "total_ghg_intensity": 20.1,
        "latitude": 40.762219,
        "longitude": -73.922995
    },
    {
        "property_name": "1111 Ward Ave LLC",
        "address_1": "1111 Ward Ave",
        "city": "Bronx",
        "postal_code": 10472,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 43200,
        "multifamily_housing_total_number_of_residential_living_units": 51,
        "year_built": 1927,
        "total_ghg_intensity": 19.8,
        "latitude": 40.826513,
        "longitude": -73.87679
    },
    {
        "property_name": "2022 Copy of Clearview 2 Bldg M-01 to M-04",
        "address_1": "16-24 200th Street",
        "city": "New York",
        "postal_code": 11357,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 35520,
        "multifamily_housing_total_number_of_residential_living_units": 80,
        "year_built": 1955,
        "total_ghg_intensity": 19.6,
        "latitude": 40.783582,
        "longitude": -73.793629
    },
    {
        "property_name": "1484 Sterling Place",
        "address_1": "1484 Sterling Place",
        "city": "Brooklyn",
        "postal_code": 11213,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 25200,
        "multifamily_housing_total_number_of_residential_living_units": 27,
        "year_built": 1922,
        "total_ghg_intensity": 19.4,
        "latitude": 40.671399,
        "longitude": -73.929639
    },
    {
        "property_name": "MP Management - 2654 Valentine ave",
        "address_1": "2654 Valentine ave",
        "city": "Bronx",
        "postal_code": 10458,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "100% Yes",
        "multifamily_housing_gross_floor_area_ft": 27900,
        "multifamily_housing_total_number_of_residential_living_units": 32,
        "year_built": 1916,
        "total_ghg_intensity": 19.3,
        "latitude": 40.865446,
        "longitude": -73.893171
    },
    {
        "property_name": "Windward RE: 2377 Creston Ave",
        "address_1": "2377 Creston Ave",
        "city": "Bronx",
        "postal_code": 10468,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 49184,
        "multifamily_housing_total_number_of_residential_living_units": 59,
        "year_built": 1924,
        "total_ghg_intensity": 18.9,
        "latitude": 40.859927,
        "longitude": -73.89968
    },
    {
        "property_name": "15 Hubert Street Condominium",
        "address_1": "15 Hubert Street",
        "city": "New York",
        "postal_code": 10013,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 30016,
        "multifamily_housing_total_number_of_residential_living_units": 13,
        "year_built": 1867,
        "total_ghg_intensity": 18,
        "latitude": 40.721425,
        "longitude": -74.009553
    },
    {
        "property_name": "2585 Grand Concourse",
        "address_1": "2585 Grand Concourse",
        "city": "Bronx",
        "postal_code": 10468,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "100% Yes",
        "multifamily_housing_gross_floor_area_ft": 29370,
        "multifamily_housing_total_number_of_residential_living_units": 27,
        "year_built": 1916,
        "total_ghg_intensity": 17.8,
        "latitude": 40.864433,
        "longitude": -73.895639
    },
    {
        "property_name": "64-01 Grand Avenue",
        "address_1": "6401 Grand Ave",
        "city": "Queens",
        "postal_code": 11378,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 14250,
        "multifamily_housing_total_number_of_residential_living_units": 14,
        "year_built": 2006,
        "total_ghg_intensity": 17.3,
        "latitude": 40.722868,
        "longitude": -73.901633
    },
    {
        "property_name": "102 Bard Avenue",
        "address_1": "102 Bard Avenue",
        "city": "Staten Island",
        "postal_code": 10310,
        "primary_property_type_self_selected": "Multifamily Housing",
        "multifamily_housing_government_subsidized_housing": "No",
        "multifamily_housing_gross_floor_area_ft": 26820,
        "multifamily_housing_total_number_of_residential_living_units": 34,
        "year_built": 1961,
        "total_ghg_intensity": 17.1,
        "latitude": 40.642445,
        "longitude": -74.108172
    }

]